; LILYGO T-SIM7000G (ESP32-WROVER-B + SIM7000G CAT-M/NB-IoT/GPS)
[env:tsim7000g]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -DTINY_GSM_MODEM_SIM7000
    -DTINY_GSM_RX_BUFFER=1024
lib_deps =
    vshymanskyy/TinyGSM@^0.12.0
    arduino-libraries/ArduinoHttpClient@^0.6.1
    bblanchon/ArduinoJson@^7.0.0
